name: Deploy to production

on:
  push:
    branches: [ main ]

jobs:
  build:
    name: Build image
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Fetch secret
        id: lockbox-secret
        uses: yc-actions/yc-lockbox@v1
        with:
          yc-sa-json-credentials: ${{ secrets.YC_SA_JSON_CREDENTIALS }}
          secret-id: ${{ secrets.LOCKBOX_ID }}

      - name: Test secrets
        run: |
          echo "DB_SOURCE=$DB_SOURCE" >> app.env
          echo "DB_DRIVER=$DB_DRIVER" >> app.env
          echo "SERVER_ADDRESS=$SERVER_ADDRESS" >> app.env
          echo "ACCESS_TOKEN_DURATION=$ACCESS_TOKEN_DURATION" >> app.env
          echo "TOKEN_SYMMETRIC_KEY=$TOKEN_SYMMETRIC_KEY" >> app.env
          cat app.env

      - name: Login to Yandex Cloud Container Registry
        id: login-cr
        uses: yc-actions/yc-cr-login@v1
        with:
          yc-sa-json-credentials: ${{ secrets.YC_SA_JSON_CREDENTIALS }}

      - name: Build, tag, and push image to Yandex Cloud Container Registry
        env:
          CR_REGISTRY: ${{ secrets.CR_REGISTRY }}
          CR_REPOSITORY: ${{ secrets.CR_REPO }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t cr.yandex/$CR_REGISTRY/$CR_REPOSITORY:$IMAGE_TAG .
          docker push cr.yandex/$CR_REGISTRY/$CR_REPOSITORY:$IMAGE_TAG

