name: Deploy to production

on:
  push:
    branches: [ main ]

jobs:
  build:
    name: Build image
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Login to Yandex Cloud Container Registry
        id: login-cr
        uses: yc-actions/yc-cr-login@v1
        with:
          yc-sa-json-credentials: ${{ secrets.YC_SA_JSON_CREDENTIALS }}

      - name: Load secrets and save to app.env
        run: curl -X GET -H "Authorization: Bearer ${{ secrets.IAM_TOKEN }}" https://payload.lockbox.api.cloud.yandex.net/lockbox/v1/secrets/e6qqr6f1ae98fp33mfi1/payload | jq -r '.["entries"]|map("\(.key)=\(.textValue)")|.[]' > app.env

      - name: Build, tag, and push image to Yandex Cloud Container Registry
        env:
          CR_REGISTRY: ${{ secrets.CR_REGISTRY }}
          CR_REPOSITORY: ${{ secrets.CR_REPO }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t cr.yandex/$CR_REGISTRY/$CR_REPOSITORY:$IMAGE_TAG .
          docker push cr.yandex/$CR_REGISTRY/$CR_REPOSITORY:$IMAGE_TAG

